version: '3.4'

services:
  dockerpytorchsrvtest:
    image: pytorchsrv
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
      - 8081:8081
    volumes:
      - type: bind
        source: ./model_mars/xsumm-sf.mar
        target: /home/model-server/model-store/xsumm-sf.mar
      - type: bind
        source: ./model_mars/xsenti-nlptown.mar
        target: /home/model-server/model-store/xsenti-nlptown.mar


    # volumes:
    #  - xsumm_mar:/home/model-server/model-store/
volumes:
  xsumm_mar:
    
