version: '3.4'

services:
  dockerpytorchsrvtest:
    image: dockerpytorchsrvtest
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
      - 8081:8081
    volumes:
      - type: bind
        source: ./xsumm-sf.mar
        target: /home/model-server/model-store/xsumm-sf.mar
    # volumes:
    #  - xsumm_mar:/home/model-server/model-store/
volumes:
  xsumm_mar:
    
