models:
	curl http://localhost:8081/models/

regmodel:
	# curl -X POST "http://localhost:8081/models?url=https://lotus-ds-resources.s3.eu-west-1.amazonaws.com/models/xsumm-sf.mar&initial_workers=1&synchronous=true&model_name=xsumm&batch_size=1"
	curl -X POST "http://localhost:8081/models?url=xsumm-sf.mar&initial_workers=1&synchronous=true&model_name=xsumm&batch_size=1"